# https://www.howtoforge.com/tutorial/how-to-create-docker-images-with-dockerfile/
# Download base image ubuntu 20.04
FROM mysql:8.0

# LABEL about the custom image
LABEL maintainer="admin@sysadminjournal.com"
LABEL version="0.1"
LABEL description="This is custom Docker Image for \
the PHP-FPM and Nginx Services."
